---
name: semantic_release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: zenrock-devops
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.RELEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
      - name: Install dependencies
        run: npm clean-install
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          GIT_AUTHOR_EMAIL: 'semanticrelease@zenrocklabs.io'
          GIT_COMMITTER_EMAIL: 'semanticrelease@zenrocklabs.io'
          GIT_AUTHOR_NAME: '@semanticrelease'
          GIT_COMMITTER_NAME: '@semanticrelease'
        run: npx semantic-release
